version: '3'

services:
  backend:
    build: backend/
    restart: always
    networks:
      - back-tier
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db
  db:
    image: mysql:latest
    build: db/
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - back-tier
  frontend:
    build: frontend/
    restart: always
    networks:
      - front-tier
      - back-tier
    depends_on:
      - backend
volumes:
  db:
networks:
  back-tier:
  front-tier:
